### ISSUE TITLE
Error in NotoSansTamil-MM.glyphs

### ISSUE THREAD

**Issue by zjusbo** [googlei18n/noto-source#71]
Steps to reproduce:
0. update noto-source and fontmake to latest version.
1. change dir to noto-source/src/NotoSansTamil/
2. run following command
fontmake -g NotoSansTamil-MM.glyphs --mti-source NotoSansTamil-MM.plist -i --no-production-names 

Got following error

Traceback (most recent call last):
  File "/usr/local/google/home/bosong/playground/fontmake/fontmake/bin/fontmake", line 11, in <module>
    load_entry_point('fontmake', 'console_scripts', 'fontmake')()
  File "/usr/local/google/home/bosong/playground/fontmake/Lib/fontmake/__main__.py", line 182, in main
    project.run_from_glyphs(glyphs_path, **args)
  File "/usr/local/google/home/bosong/playground/fontmake/Lib/fontmake/font_project.py", line 352, in run_from_glyphs
    designspace_path, instance_data=instance_data, **kwargs)
  File "/usr/local/google/home/bosong/playground/fontmake/Lib/fontmake/font_project.py", line 408, in run_from_designspace
    interpolate_layout_from=interpolate_layout_from, **kwargs)
  File "/usr/local/google/home/bosong/playground/fontmake/Lib/fontmake/font_project.py", line 458, in run_from_ufos
    ufos, remove_overlaps, mti_paths=mti_paths, **kwargs)
  File "/usr/local/google/home/bosong/playground/fontmake/Lib/fontmake/font_project.py", line 149, in build_otfs
    self.save_otfs(ufos, **kwargs)
  File "/usr/local/google/home/bosong/playground/fontmake/fontmake/local/lib/python2.7/site-packages/fontTools/misc/loggingTools.py", line 372, in wrapper
    return func(*args, **kwds)
  File "/usr/local/google/home/bosong/playground/fontmake/Lib/fontmake/font_project.py", line 265, in save_otfs
    mtiFeaFiles=mti_paths[name] if mti_paths is not None else None,
KeyError: u'NotoSansTamil-Thin'

I'm suspecting its an error in plist. The plist does not contain an entry for NotoSansTamil-Thin. However, previous build does not show this error, which is quite weird.

**Comment by zjusbo** [comment]
I dropped the --mti-source option and then it goes fine. 
fontmake -g NotoSansTamil-MM.glyphs -i --no-production-names

**Comment by behdad** [comment]
> I dropped the --mti-source option and then it goes fine.

No, you can't just do that!

**Comment by brawer** [comment]
@zjusbo, the reason is that these MTI files contain critical information. Without them, OpenType layout (the glyph substitution and positioning) won’t work — try entering some Tamil text in FontView. In the current .plist file, the GPOS entry for “NotoSansTamil-Light” points to “Noto Sans Tamil 26-100 GPOS.txt”, but weight=26 is actually Thin and not Light (at least in the PostScript name, which is what the keys in *.plist seem to use). Can you try renaming “NotoSansTamil-Light” to “NotoSansTamil-Thin” in the .plist file and see if that works?

**Comment by anthrotype** [comment]
The mti source files in noto-source repo are only for the masters, not for the instances. The latter GPOS are interpolated with --interpolate-binary-layout, with a second fontmake call. The first call to fontmake builds the master TTFs with --mti-sources option. 
E.g.
https://github.com/googlei18n/fontmake/commit/1e15d6f485b343884b56225875adaecbaf3d60e4

**Comment by zjusbo** [comment]
@brawer Thanks for the info. I tried but s/Light/Thin does not work either. As @anthrotype mentioned, we need two steps to generate all the instances. 

replace ${src} with actual font name.

First: (make the master)

> fontmake -g "${src}.glyphs" --mti-source "${src}.plist" --no-production-names

Second: (interpolate to generate instances)

> fontmake -g "${src}.glyphs" -i --interpolate-binary-layout --no-production-names

Everything goes fine after I run these two steps in order. 

**For those who encountered same errors, Please run the commands above in order.** 

However, I encountered another error when executing the second command:

> fontmake -g NotoSansTamil-MM.glyphs -i --interpolate-binary-layout --no-production-names



> INFO:fontmake.font_project:Saving OTF for NotoSansTamil-Thin
> Index of base master: 1
> **Building variable font**
> Loading master fonts
> Axes:
> {'weight': (100.0, 400.0, 900.0), 'width': (70.0, 100.0, 100.0)}
> Location: {'width': 100.0, 'weight': 26.0}
> Master locations:
> [{'weight': 26.0, 'width': 100.0},
>  {'weight': 90.0, 'width': 100.0},
>  {'weight': 151.0, 'width': 100.0},
>  {'weight': 190.0, 'width': 100.0},
>  {'weight': 26.0, 'width': 70.0},
>  {'weight': 90.0, 'width': 70.0},
>  {'weight': 190.0, 'width': 70.0}]
> Normalized location: {'width': 0.0, 'weight': -1.0}
> Normalized master locations:
> [{'weight': -1.0, 'width': 0.0},
>  {'weight': -1.0, 'width': 0.0},
>  {'weight': -0.83, 'width': 0.0},
>  {'weight': -0.7, 'width': 0.0},
>  {'weight': -1.0, 'width': -1.0},
>  {'weight': -1.0, 'width': -1.0},
>  {'weight': -0.7, 'width': -1.0}]
> Traceback (most recent call last):
>   File "/usr/local/google/home/bosong/fonttools/dev/bin/fontmake", line 11, in <module>
>     load_entry_point('fontmake', 'console_scripts', 'fontmake')()
>   File "/usr/local/google/home/bosong/fontmake/Lib/fontmake/__main__.py", line 182, in main
>     project.run_from_glyphs(glyphs_path, **args)
>   File "/usr/local/google/home/bosong/fontmake/Lib/fontmake/font_project.py", line 379, in run_from_glyphs
>     designspace_path, instance_data=instance_data, **kwargs)
>   File "/usr/local/google/home/bosong/fontmake/Lib/fontmake/font_project.py", line 435, in run_from_designspace
>     interpolate_layout_from=interpolate_layout_from, **kwargs)
>   File "/usr/local/google/home/bosong/fontmake/Lib/fontmake/font_project.py", line 475, in run_from_ufos
>     ufos, remove_overlaps, **kwargs)
>   File "/usr/local/google/home/bosong/fontmake/Lib/fontmake/font_project.py", line 177, in build_otfs
>     self.save_otfs(ufos, **kwargs)
>   File "/usr/local/google/home/bosong/fonttools/dev/local/lib/python2.7/site-packages/fontTools/misc/loggingTools.py", line 372, in wrapper
>     return func(*args, **kwds)
>   File "/usr/local/google/home/bosong/fontmake/Lib/fontmake/font_project.py", line 305, in save_otfs
>     interpolate_layout_from, loc, finder)
>   File "/usr/local/google/home/bosong/fonttools/dev/local/lib/python2.7/site-packages/**fontTools/varLib/interpolate_layout.py**", line 79, in **interpolate_layout**
>     model = models.VariationModel(master_locs)
>   File "/usr/local/google/home/bosong/fonttools/dev/local/lib/python2.7/site-packages/fontTools/varLib/models.py", line 148, in __init__
>     keyFunc = self.getMasterLocationsSortKeyFunc(locations, axisOrder=axisOrder)
>   File "/usr/local/google/home/bosong/fonttools/dev/local/lib/python2.7/site-packages/fontTools/varLib/models.py", line 159, in getMasterLocationsSortKeyFunc
>     assert {} in locations, "Base master not found."
> AssertionError: Base master not found.

It's an error raised by varLib. But not sure if it's a bug in font source, varLib or it's dependencies.
