### ISSUE TITLE
Build is broken

### ISSUE THREAD

**Issue by brawer** [googlei18n/noto-source#72]
```sh
$ git clone --recursive https://github.com/googlei18n/noto-source.git
$ cd noto-source/
$ ./build setup
[...]
  Running setup.py install for fontmake ... done
Successfully installed MutatorMath-2.0.3 booleanOperations-0.7.0 defcon-0.3.1 fontmake-1.2.0 fonttools-3.9.1 glyphsLib-1.6.0 ufo2ft-0.4.1

$ ./build all
==== building src/gNotoNastaliqUrdu.glyphs ====
Traceback (most recent call last):
  File "/home/sascha/src/noto-source/env/bin/fontmake", line 11, in <module>
    load_entry_point('fontmake==1.2.0', 'console_scripts', 'fontmake')()
  File "/home/sascha/src/noto-source/env/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 560, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/home/sascha/src/noto-source/env/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2648, in load_entry_point
    return ep.load()
  File "/home/sascha/src/noto-source/env/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2302, in load
    return self.resolve()
  File "/home/sascha/src/noto-source/env/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2308, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/home/sascha/src/noto-source/env/local/lib/python2.7/site-packages/fontmake/__main__.py", line 18, in <module>
    from fontmake.font_project import FontProject
  File "/home/sascha/src/noto-source/env/local/lib/python2.7/site-packages/fontmake/font_project.py", line 40, in <module>
    from ufo2ft.makeotfParts import FeatureOTFCompiler
ImportError: No module named makeotfParts
```

**Comment by anthrotype** [comment]
https://github.com/googlei18n/noto-source/pull/70
