### ISSUE TITLE
enhancement request: should "make -B src/NotoEmoji/NotoEmoji-Regular.ufo" work?

### ISSUE THREAD

**Issue by marekjez86** [googlei18n/noto-source#9]
we added src/NotoEmoji/NotoEmoji-Regular.ufo to directory.
however, make -B src/NotoEmoji/NotoEmoji-Regular.ufo appears to fail. How would one build this?

```
make -B src/NotoEmoji/NotoEmoji-Regular.ufo
bash build.sh build_one src/NotoEmoji/NotoEmoji-Regular.ufo
>> Checking Glyphs source for illegal glyph names
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/2.7/bin/fontmake", line 9, in <module>
    load_entry_point('fontmake==1.0', 'console_scripts', 'fontmake')()
  File "/Users/marekj/Library/Python/2.7/lib/python/site-packages/fontmake-1.0-py2.7.egg/fontmake/__main__.py", line 73, in main
  File "/Users/marekj/Library/Python/2.7/lib/python/site-packages/fontmake-1.0-py2.7.egg/fontmake/font_project.py", line 246, in run_from_glyphs
  File "/Users/marekj/Library/Python/2.7/lib/python/site-packages/fontmake-1.0-py2.7.egg/fontmake/font_project.py", line 53, in preprocess
IOError: [Errno 21] Is a directory: 'src/NotoEmoji/NotoEmoji-Regular.ufo'
make: *** [src/NotoEmoji/NotoEmoji-Regular.ufo] Error 1
```

**Comment by jamesgk** [comment]
Should be fixed by https://github.com/googlei18n/noto-source/commit/508c42d4072e4c2425a7d1a84c9fd440f9698c60
