### ISSUE TITLE
cannot build sources: problem in newest glyphslib

### ISSUE THREAD

**Issue by themaddoctor** [googlei18n/noto-source#95]
My glyphsLib is from git 20171016 (three days ago; last time changed).
Fontmake is 1.3.0.

Traceback (most recent call last):
  File "/usr/bin/fontmake", line 11, in <module>
    load_entry_point('fontmake==1.3.0', 'console_scripts', 'fontmake')()
  File "/usr/lib/python2.7/site-packages/fontmake/__main__.py", line 183, in main
    project.run_from_glyphs(glyphs_path, **args)
  File "/usr/lib/python2.7/site-packages/fontmake/font_project.py", line 376, in run_from_glyphs
    glyphs_path, family_name, mti_source=mti_source)
  File "/usr/lib/python2.7/site-packages/fontTools/misc/loggingTools.py", line 372, in wrapper
    return func(*args, **kwds)
  File "/usr/lib/python2.7/site-packages/fontmake/font_project.py", line 77, in build_master_ufos
    family_name=family_name)
  File "/usr/lib/python2.7/site-packages/glyphsLib/__init__.py", line 93, in build_masters
    filename, include_instances=True, family_name=family_name)
  File "/usr/lib/python2.7/site-packages/glyphsLib/__init__.py", line 72, in load_to_ufos
    family_name=family_name, debug=debug)
  File "/usr/lib/python2.7/site-packages/glyphsLib/builder.py", line 172, in to_ufos
    layer_name = layer.name
  File "/usr/lib/python2.7/site-packages/glyphsLib/classes.py", line 2349, in name
    return master.name
  File "/usr/lib/python2.7/site-packages/glyphsLib/classes.py", line 1297, in name
    names.add("Italic")
AttributeError: 'list' object has no attribute 'add'

**Comment by themaddoctor** [comment]
If instead, I use python3:

==== building src/NotoSans-ItalicMM.glyphs ====
INFO:fontmake.font_project:Building master UFOs and designspace from Glyphs source
INFO:glyphsLib:Parsing .glyphs file
INFO:glyphsLib:Loading to UFOs
Traceback (most recent call last):
  File "/usr/bin/fontmake", line 11, in <module>
    load_entry_point('fontmake==1.3.0', 'console_scripts', 'fontmake')()
  File "/usr/lib/python3.6/site-packages/fontmake/__main__.py", line 183, in main
    project.run_from_glyphs(glyphs_path, **args)
  File "/usr/lib/python3.6/site-packages/fontmake/font_project.py", line 376, in run_from_glyphs
    glyphs_path, family_name, mti_source=mti_source)
  File "/usr/lib/python3.6/site-packages/fontTools/misc/loggingTools.py", line 372, in wrapper
    return func(*args, **kwds)
  File "/usr/lib/python3.6/site-packages/fontmake/font_project.py", line 77, in build_master_ufos
    family_name=family_name)
  File "/usr/lib/python3.6/site-packages/glyphsLib/__init__.py", line 93, in build_masters
    filename, include_instances=True, family_name=family_name)
  File "/usr/lib/python3.6/site-packages/glyphsLib/__init__.py", line 72, in load_to_ufos
    family_name=family_name, debug=debug)
  File "/usr/lib/python3.6/site-packages/glyphsLib/builder.py", line 115, in to_ufos
    if font.appVersion < 895:
TypeError: '<' not supported between instances of 'str' and 'int'

**Comment by anthrotype** [comment]
thanks for the report.
it looks like a tooling issue so the right place to file this is the upstream glyphsLib repository, like you did already:
https://github.com/googlei18n/glyphsLib/issues/242
